### ISSUE TITLE
Allow the use of GPIO with non-root user

### ISSUE THREAD

**Issue by teopost** [UieLinux/coding-for-school-os#9]
It is not acceptable to ask the user to become root to turn on an LED

**Comment by gallochri** [comment]
Example with gpio22:
# echo 22  > /sys/class/gpio/export
# echo out > /sys/class/gpio/gpio22/direction
# chown root:gpio /sys/class/gpio/gpio22/value
# chmod g+w /sys/class/gpio/gpio22/value

Now all users from the "gpio" group can control the gpio22.
You must put a script during the boot to make it permanent.
NOT TESTED.

**Comment by teopost** [comment]
I would like enable all gpio to pi user
